stages:
  - prepare
  - cs-fix
  - lint
  - deploy

include:
  # Prepare
  - project: 'intern/runner-templates'
    ref: "12.7"
    file: '/symfony/install-dependencies.yml'

  # CS fix
  - project: 'intern/runner-templates'
    ref: "12.7"
    file: '/php/code-style-fixer.yml'

  # Lint
  - project: 'intern/runner-templates'
    ref: "12.7"
    file: '/php/phan.yml'
  - project: 'intern/runner-templates'
    ref: "12.7"
    file: '/php/composer-require-checker.yml'
  - project: 'intern/runner-templates'
    ref: "12.7"
    file: '/php/composer-unused.yml'
  - project: 'intern/runner-templates'
    file: '/deploy/deploy.yml'
    ref: "12.7"

install-dependencies:
  before_script:
    - /bin/true

code-style-fixer:
  variables:
    PHP_CS_FIXER_IGNORE_ENV: 'yes' # Required to our current php-cs-fixer with php8.2, needs to be removed

deploy-staging:
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule" || $CI_PIPELINE_SOURCE == "merge_request_event"
      when: never
    - if: $CI_COMMIT_REF_NAME == "master" || $CI_COMMIT_BRANCH
      when: on_success
    - when: never

deploy-production:
  rules:
    - if: $CI_COMMIT_TAG
      when: on_success
    - when: never
